Repository intel/container-experience-kits, pull requests merged in 2020-03, with the labels that each got.

#50 add role for updating git version
  roles/git2-install/tasks/main.yml
  roles/git2-install/vars/main.yml
Labels: bugfix

#52 use pip to install netaddr instead of OS package manager
  roles/k8s-all-preconfigure/tasks/main.yml
Labels: bugfix

#51 Update OVS and DPDK versions
  roles/dpdk-install/vars/main.yml
  roles/userspace-cni-install/defaults/main.yml
Labels: dependencies

#49 Add sst-bf configuration
  examples/host_vars/node1.yml
  playbooks/infra/infra_setup.yml
  roles/sst-bf-configure/defaults/main.yml
  roles/sst-bf-configure/tasks/main.yml
Labels: enhancement

#39 Add tas-install role
  examples/group_vars/all.yml
  playbooks/intel/bmra_features.yml
  roles/cluster-defaults/defaults/main.yml
  roles/git2-install/tasks/main.yml
  roles/golang-install/defaults/main.yml
  roles/tas-install/charts/tas-policy-crd.yml
  roles/tas-install/charts/telemetry-aware-scheduling/.helmignore
  roles/tas-install/charts/telemetry-aware-scheduling/Chart.yaml
  roles/tas-install/charts/telemetry-aware-scheduling/templates/NOTES.txt
  roles/tas-install/charts/telemetry-aware-scheduling/templates/_helpers.tpl
  roles/tas-install/charts/telemetry-aware-scheduling/templates/tas-deployment.yml
  roles/tas-install/charts/telemetry-aware-scheduling/templates/tas-policy.yml
  roles/tas-install/charts/telemetry-aware-scheduling/templates/tas-rbac-accounts.yml
  roles/tas-install/charts/telemetry-aware-scheduling/templates/tas-service.yml
  roles/tas-install/charts/telemetry-aware-scheduling/templates/tas-tls-secret.yml
  roles/tas-install/charts/telemetry-aware-scheduling/values.yaml
  roles/tas-install/defaults/main.yml
  roles/tas-install/tasks/main.yml
  roles/tas-install/tasks/prometheus.yml
  roles/tas-install/tasks/prometheus_custom_metrics.yml
  roles/tas-install/tasks/prometheus_node_exporter.yml
  roles/tas-install/tasks/tas.yml
  roles/tas-install/templates/node-exporter-values.yml.j2
  roles/tas-install/templates/prometheus-adapter-rbac.yml.j2
  roles/tas-install/templates/prometheus-adapter-values.yml.j2
  roles/tas-install/templates/prometheus-values.yml.j2
  roles/tas-install/templates/tas-values.yml.j2
  roles/tas-install/vars/main.yml
Labels: enhancement

#57 use fixed versions of setuptools and wheel
  roles/net-attach-defs-create/tasks/main.yml
Labels: bugfix
